version: "3.8"
services:
  vanilla-database:
    container_name: vanilla-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: devhyuk214/vanilla-database
    environment:
      - MYSQL_DATABASE=vanilla
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  vanilla-redis:
    container_name: vanilla-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: devhyuk214/vanilla-redis
    ports:
      - "6379:6379"
  vanilla-zookeeper:
    image: wurstmeister/zookeeper
    container_name: vanilla-zookeeper
    ports:
      - "2181:2181"
  vanilla-kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: vanilla-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: vanilla-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock